name: Base functionality pipeline for UA website
run-name: test from user @${{github.actor}}

on:
  push:
    branches:
#      - main
  workflow_dispatch:

jobs:
  build:
    runs-on:
      ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - uses: browser-actions/setup-firefox@v1
      - run: firefox --version

      - uses: browser-actions/setup-geckodriver@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: geckodriver --version
      - name: Download Selenium Server
        run: |
          curl -LO https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
      - name: List Downloaded Files
        run: ls -l
      - run: echo $PATH
      - name: Run selenium server standalone
        run: java -jar -Dwebdriver.gecko.driver=/opt/hostedtoolcache/geckodriver/0.33.0/x64/geckodriver selenium-server-standalone-3.141.59.jar &

#      - name: Run UI tests (add to cart test)
#        run: mvn clean test -Dsuite=UA_suites/UA_addToCart_test
      - name: Run UI tests (login test)
#        if: always()
        run: mvn clean test -Dsuite=UA_suites/UA_login_test
#      - name: Run UI tests (search test)
#        if: always()
#        run: mvn clean test -Dsuite=UA_suites/UA_search_test
#      - name: Run UI tests (sort test)
#        if: always()
#        run: mvn clean test -Dsuite=UA_suites/UA_sort_test
