name: Base functionality pipeline for UA website
run-name: test from user @${{github.actor}}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on:
      ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - uses: browser-actions/setup-firefox@v1
      - run: firefox --version
      - run: echo $PATH
      - uses: browser-actions/setup-geckodriver@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: geckodriver --version
      - name: Download Selenium Server
        run: |
          curl -LO https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
      - name: List Downloaded Files
        run: ls -l
      - name: Run selenium server standalone
        run: java -jar -Dwebdriver.gecko.driver=/opt/selenium/geckodriver selenium-server-standalone-3.141.59.jar &
      - name: Run UI tests
        run: mvn clean test -Dsuite=UA_suites/UA_LS