name: Base functionality pipeline for UA website
run-name: test from user @${{github.actor}}

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on:
      ubuntu-latest
    steps:
      - name: Set up Firefox
        uses: mozilla/geckodriver@v0.30.0
      - uses: actions/checkout@v3
      - name: Set up Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Run UI tests
        run: mvn clean test -Dsuite=UA_suites/UA_LS
