name: Pipeline with secrets from gh
run-name: test from user @${{github.actor}}

on:
  workflow_dispatch:

jobs:
  build:
    runs-on:
      ubuntu-latest

    steps:
      - name: checking credentials
        run: echo "email - ${{ secrets.EMAIL }}"
